theme: jekyll-theme-slate
title: Projeto de Análise e Projeto de Sistemas - E-Commerce
description: Essa página descreve o projeto de Análise e Projeto de Sistemas para uma aplicação de E-Commerce. Nessa aplicação os clientes poderão, se registrar e logar como usuários, adicionar produtos em seus carrinhos, efetuar a compra dos produtos no carrinho, listar e buscar produtos, rastrear o seu pedidos e avaliar os produtos comprados.
